language: haxe

# TravisCI by default run on linux.
# Let's enable both linux and mac builds because why not?
os:
  - linux
  - osx

# Let's use Ubuntu Trusty instead of Precise, which reached its EOL on April 28, 2017.
dist: trusty

# Test with Haxe 3.4.7 and Haxe development.
haxe:
  - "3.4.7"
  - development

#neko: "2.2.0"

addons:
  # This is the preferred way to install apt packages.
  # However, it only allow some but not all packages.
  # Alternatively, we can use `sudo apt-get install ...` in the `install:` section.
  # http://docs.travis-ci.com/user/apt/#Adding-APT-Packages
  apt:
    packages:
      # Flash
      - libglib2.0
      - libfreetype6

install:
  # Download and setup a standalone flash player debugger
  - haxe Tests/flash/install.hxml
  # Install haxelibs
  - haxelib list

script:
  - haxe Tests/build-js.hxml           && node Tests/bin/Run.js
  - haxe Tests/build-flash.hxml -D fdb && haxe Tests/flash/run.hxml Tests/bin/Run.swf
